version: '2.1'

services:
  nginx:
    image: metube-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
  
  api:
    image: metube-api:latest
    environment:
      - METUBE_ENVIRONMENT=development
      - METUBE_DEBUG=TRUE
      - METUBE_SECRET_KEY=ThisIsANotSoSecretSecretKey
      - METUBE_ALLOWED_HOSTS=*
      - METUBE_DATABASE_URL=mysql://metube:metube@database:3306/metube
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
   
  database:
    image: mysql:5.7.24
    environment:
      - MYSQL_USER=metube
      - MYSQL_PASSWORD=metube
      - MYSQL_DATABASE=metube
      - MYSQL_ROOT_PASSWORD=itsasecret
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  
  test:
    image: metube-api:latest
    environment:
      - METUBE_ENVIRONMENT=test
      - METUBE_DEBUG=TRUE
      - METUBE_SECRET_KEY=ThisIsANotSoSecretSecretTestKey
    entrypoint: ./test-entrypoint.sh
