version: '2.1'

services:
  nginx:
    build: ./nginx
    # restart: always
    # image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    # build: ./backend
    # restart: always
    image: metube:latest
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn mydjango.wsgi -b 0.0.0.0:8000"
    depends_on:
      database:
        condition: service_healthy

    # volumes:
      # - ./src:/src
    # expose:
      # - "8000"
    # ports:
      # - "8000:8000"

  database:
    image: mysql:5.7.23
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=metube
      - MYSQL_ROOT_PASSWORD=itsasecret
    ports:
      - 19090:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
