setup: &default
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "metube/requirements.txt" }}
      - run:
          name: build images
          command: |
            make build
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "metube/requirements.txt" }}
  
  test:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "metube/requirements.txt" }}
      - run:
          name: run tests
          command: |
            make test
      - store_artifacts:
          path: test-reports
          destination: test-reports
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
