# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/requirements.txt" }}
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt
            pip install docker-compose
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "backend/requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            docker-compose up -d
            docker-compose exec api python manage.py migrate
            docker-compose exec api python manage.py test
            # . venv/bin/activate
            # python backend/metube/manage.py test --settings=metube.settings.test
      
      - store_artifacts:
          path: test-reports
          destination: test-reports
  
  push-image:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - setup-remote-docker
      - run:
         name: install aws and docker-compose
         command: |
           curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
           unzip awscli-bundle.zip
           sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
           pip install docker-compose
      - run:
         name: "Log in to AWS ECR"
         command: eval $(aws ecr get-login --region eu-central-1 --no-include-email)
      - run:
          name: Build docker containers and push it
          command: |
            aws s3 cp s3://django-metube/config/production_settings.py backend/metube/metube/settings/settings.py
            
            docker build -t metube/api backend/
            docker-compose up -d
            docker-compose exec api python manage.py migrate
            
            docker tag metube/api:latest 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/api:latest
            docker push 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/api:latest
            
            docker build -t metube/nginx nginx/
            docker tag metube/nginx:latest 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/nginx:latest
            docker push 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/nginx:latest
  
  deploy:
    docker:
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
         name: install boto3
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install boto3
      - run:
         name: "Force redeployment"
         command: |
           . venv/bin/activate
           python restart-service-tasks.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - push-image:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - push-image
          filters:
            branches:
              only:
                - master
