# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

setup: &default
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *default
    steps:
      - checkout    
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r backend/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "backend/requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - store_artifacts:
          path: test-reports
          destination: test-reports
  
  push-image:
    <<: *default
    steps:
      - checkout
      - setup-remote-docker
      - run:
         name: install aws
         command: |
           curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
           unzip awscli-bundle.zip
           sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: Update settings with secrets
          command: |
            aws s3 cp s3://django-metube/config/production_settings.py backend/metube/metube/settings/settings.py
      - run:
         name: "Log in to AWS ECR"
         command: eval $(aws ecr get-login --region eu-central-1 --no-include-email)
      - run:
          name: Build docker containers and push it
          command: |
            docker build -t metube-api:latest backend/
            docker build -t metube-nginx:latest nginx/
            
            docker tag metube-api:latest 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/api:latest
            docker push 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/api:latest
            
            docker tag metube-nginx:latest 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/nginx:latest
            docker push 624540041426.dkr.ecr.eu-central-1.amazonaws.com/metube/nginx:latest
  
  deploy:
    <<: *default
    steps:
      - checkout
      - run:
         name: install boto3
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install boto3
      - run:
         name: "Force redeployment"
         command: |
           . venv/bin/activate
           python restart-service-tasks.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - push-image:
          requires:
            - build
          # filters:
            # branches:
              # only:
                # - master
      - deploy:
          requires:
            - push-image
          filters:
            branches:
              only:
                - master
