#%RAML 1.0
title: Metube Authentication Services
version: 1.0
baseUri: https://api.metube.dk/authentication
mediaType: application/json
securitySchemes:
  auth:
    type: Pass Through
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid auth token by setting value to "Bearer {accessToken}". {accessToken} is returned upon creation or login.
traits:
  authorized:
    description: Request requires authorization.
    responses:
      401:
        body:
          examples: [
            {
              "error": "Invalid Header"
            },
            {
              "error": "Token not found"
            }
          ]

types:
  loginDTO:
    type: object
    properties:
      username: string
      password: string
  loginResponseDTO:
    type: object
    properties:
      username: string
      token: string

/login:
  post:
    is: [authorized]
    securedBy: [auth]
    description: Login using supplied credentials
    body:
      type: loginDTO
      example: |
        {
          "username": "some-username",
          "password": "MyVerySecretSecret",
        }
    responses:
      200:
        body:
          type: loginResponseDTO
          example: |
            {
              "username": "some-username",
              "token": "47a46f84e986440f5fd462f6f7a2cd775cca9905"
            }
      400:
        example: |
          {
            "error": "Invalid Header"
          }


/logout:
  post:
    is: [authorized]
    securedBy: [auth]
    description: Logout user matching supplied access token
    responses:
      200:
        example: |
          {
            "error": "Invalid Header"
          }

/verify:
  get:
    is: [authorized, userid]
    securedBy: [auth]
    description: Verifies supplied authentication
    responses:
      200:

